import React from 'react';
import { Divider } from "@heroui/divider";
import { ScoreResult } from './types';
import ScoreCard from './ScoreCard';

interface ResultsDisplayProps {
	result: ScoreResult;
	forExport?: boolean;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, forExport = false }) => {
	if (forExport) {
		// Export version with clean styling (no dark borders)
		return (
			<div className="space-y-8 p-8 bg-gradient-to-br from-blue-50 to-purple-50 min-h-[600px] border-4 border-blue-200 rounded-2xl shadow-2xl">
				<div className="text-center mb-8">
					<div className="text-6xl font-black text-blue-600 mb-4">
						IELTS Assessment Results
					</div>
					<div className="text-lg text-gray-600 font-medium">
						Professional Writing Evaluation
					</div>
				</div>

				{/* Overall Score */}
				<div className="text-center">
					<div className="text-8xl font-black text-green-600 drop-shadow-lg">
						{result.OVERALL}
					</div>
					<div className="text-2xl font-semibold text-gray-700 mb-2">
						Overall Band Score
					</div>
					<div className="text-lg text-gray-600 bg-gray-100 px-4 py-2 rounded-full inline-block">
						⏱️ Processing time: {result.time.toFixed(2)}s
					</div>
				</div>

				<Divider className="my-8" />

				{/* Individual Scores */}
				<div className="grid grid-cols-2 gap-6">
					<ScoreCard
						title="Task Response"
						score={result.TR}
						colorClass="text-blue-700"
						bgClass="bg-gradient-to-br from-blue-50 to-blue-100"
						borderClass="border-blue-300"
					/>
					<ScoreCard
						title="Coherence & Cohesion"
						score={result.CC}
						colorClass="text-green-700"
						bgClass="bg-gradient-to-br from-green-50 to-green-100"
						borderClass="border-green-300"
					/>
					<ScoreCard
						title="Lexical Resource"
						score={result.LR}
						colorClass="text-purple-700"
						bgClass="bg-gradient-to-br from-purple-50 to-purple-100"
						borderClass="border-purple-300"
					/>
					<ScoreCard
						title="Grammatical Accuracy"
						score={result.GA}
						colorClass="text-orange-700"
						bgClass="bg-gradient-to-br from-orange-50 to-orange-100"
						borderClass="border-orange-300"
					/>
				</div>

				<div className="text-center mt-8 pt-6 border-t-2 border-gray-300">
					<div className="text-gray-600 font-medium text-lg">
						📚 Generated by IELTS Assessment Tool
					</div>
					<div className="text-gray-500 text-sm mt-1">
						{new Date().toLocaleDateString()} • Professional AI-powered evaluation
					</div>
				</div>
			</div>
		);
	}

	// Modal version with original HeroUI styling
	return (
		<div className="space-y-6">
			{/* Overall Score */}
			<div className="text-center">
				<div className="text-4xl font-bold text-primary mb-2">
					{result.OVERALL}
				</div>
				<div className="text-lg text-gray-600 dark:text-gray-400">
					Overall Band Score
				</div>
				<div className="text-sm text-gray-500 mt-1">
					Processing time: {result.time.toFixed(2)}s
				</div>
			</div>

			<Divider />

			{/* Individual Scores */}
			<div className="grid grid-cols-2 gap-4">
				<div className="text-center p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
					<div className="font-semibold text-sm text-blue-700 dark:text-blue-300">Task Response</div>
					<div className="text-2xl font-bold text-blue-600 dark:text-blue-400">{result.TR}</div>
				</div>
				<div className="text-center p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
					<div className="font-semibold text-sm text-green-700 dark:text-green-300">Coherence & Cohesion</div>
					<div className="text-2xl font-bold text-green-600 dark:text-green-400">{result.CC}</div>
				</div>
				<div className="text-center p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-200 dark:border-purple-800">
					<div className="font-semibold text-sm text-purple-700 dark:text-purple-300">Lexical Resource</div>
					<div className="text-2xl font-bold text-purple-600 dark:text-purple-400">{result.LR}</div>
				</div>
				<div className="text-center p-4 bg-orange-50 dark:bg-orange-900/20 rounded-lg border border-orange-200 dark:border-orange-800">
					<div className="font-semibold text-sm text-orange-700 dark:text-orange-300">Grammatical Accuracy</div>
					<div className="text-2xl font-bold text-orange-600 dark:text-orange-400">{result.GA}</div>
				</div>
			</div>
		</div>
	);
};

export default ResultsDisplay;
